### ISSUE TITLE
[Search page] Core datasets appear not on the top of the search result

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#193] opened 2018-02-01 08:57 UTC
Reported here: datahq/datahub-qa#70

We want to show `core` datasets first prior others

## Acceptance criteria

* [x] The `core` user should appear first

### How to reproduce: 

* Go to '\search` page and search for `gdp`

### Output

`core` datasets appear did not appear first in the result list

**Comment by zelima** [comment] 2018-02-21 05:04
FIXED/DUPLICATE of https://github.com/datahq/metastore/issues/27

**Comment by Mikanebu** [comment] 2018-02-22 12:04
If I search for `Mauna Loa`, the core dataset is not on the top.

**Comment by AcckiyGerman** [comment] 2018-03-01 11:47
If I search for Mauna Loa, the core dataset is not on the top :cry:

**Closed** 2018-03-01 11:49 UTC
Labels: duplicate
