### ISSUE TITLE
Search page should not search by connecting words (at least incide the README), like:  in, at, on, a, the, ...

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#194] opened 2018-02-01 09:01 UTC
Reported here: datahq/datahub-qa#69

We want to improve our search, so it will not return search by connecting words (at least inside the README), like:  in, at, on, a, the, ...

## Acceptance criteria

* [x] it should found 3 datasets with 'Mauna Loa' in the readme.
* [x] it should not found 109 datasets with 'the' in the readme

### How to reproduce: 

Go to '\search' page and search 'the Mauna Loa'

### Output

'the Mauna Loa' request found 109 datasets (should be 3)

**Comment by zelima** [comment] 2018-02-21 05:01
FIXED/DUPLICATE of https://github.com/datahq/metastore/issues/28

**Closed by zelima** 2018-02-21 05:01 UTC
