### ISSUE TITLE
Publisher page shows unlisted datasets for core user

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#192] opened 2018-02-01 08:41 UTC
Reported here: datahq/datahub-qa#75

We want to show only published datasets on core user's publisher page - https://datahub.io/core

## Acceptance criteria 

* [x] Core user's page should show only published datasets

### How to reproduce 

* Load `/core` page
* check if the list contains `unlisted` or `private` datasets

### Output 

Loaded page, and found some `unlisted` datasets

**Comment by zelima** [comment] 2018-02-21 05:05
FIXED/DUPLICATE of https://github.com/datahq/metastore/issues/26

**Closed by zelima** 2018-02-21 05:05 UTC
Labels: duplicate
