### ISSUE TITLE
Search page shows some unlisted datasets

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#196] opened 2018-02-01 10:13 UTC
Reported here: datahq/datahub-qa#51

We want to show only public datasets on search page

## Acceptance criteria

* [ ] search page should show only public datasets

## Tasks

* [ ] investigate why there are some unlisted datasets
* [ ] fix

### How to reproduce

* [ ] Go to '\search` page and seach for `core`

### Output

Some unlisted packages for `core` user are visible. For example `co2-fossil-by-nation `

**Comment by zelima** [comment] 2018-02-08 06:41
DUPLICATE of https://github.com/datahq/metastore/issues/26

**Closed by zelima** 2018-02-08 06:41 UTC
Labels: duplicate
